name: ARM64 Pull and Save Docker Image

on:
  workflow_dispatch:
    inputs:
      docker_images:
        description: '请填写docker镜像名称 多个用英文逗号分开'
        required: true
        default: 'alpine:latest,busybox:stable-glibc'  # 设置默认的 Docker 镜像列表

jobs:
  pull_and_package:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install Docker 18.09.9
      run: |
        # 卸载现有 Docker（如果存在）
        sudo apt-get remove -y docker docker-engine docker.io containerd runc || true
 
        # 安装 Docker 18.09.9
        sudo apt-get update
        sudo apt-get install -y \
          apt-transport-https \
          ca-certificates \
          curl \
          gnupg-agent \
          software-properties-common
 
        # 添加 Docker 18.09.9 的官方仓库（已归档）
        curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
        sudo add-apt-repository \
          "deb [arch=arm64] https://download.docker.com/linux/ubuntu \
          $(lsb_release -cs) \
          stable"
 
        # 固定版本安装
        echo "docker-ce=18.09.9~3-0~ubuntu-$(lsb_release -cs)" | sudo tee /etc/apt/preferences.d/docker-ce
        sudo apt-get update
        sudo apt-get install -y docker-ce=18.09.9~3-0~ubuntu-$(lsb_release -cs)
 
        # 验证 Docker 版本
        docker --version

    - name: Pull Docker Images and Package
      run: |
        images="${{ github.event.inputs.docker_images }}"
          IFS=',' read -r -a image_array <<< "$images"
          for image in "${image_array[@]}"; do
            docker pull "${image}" --platform "linux/arm64"
            image_name="${image//\//_}"
            image_name="${image_name//:/_}"
            docker save "${image}" -o "${image_name}-arm64.tar"
            gzip -c "${image_name}-arm64.tar" > "${image_name}-arm64.tar.gz"
            rm "${image_name}-arm64.tar"
          done

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: my-artifact
        path: ${{ github.workspace }}/*.tar.gz
        retention-days: 1  # 将保留天数设置为 1 天 最多可设置90天

