name: ARM64 Pull and Save Docker Image

on:
  workflow_dispatch:
    inputs:
      docker_images:
        description: '请填写docker镜像名称 多个用英文逗号分开'
        required: true
        default: 'alpine:latest,busybox:stable-glibc'  # 设置默认的 Docker 镜像列表

jobs:
  pull_and_package:
    runs-on: ubuntu-20.04

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install Docker 18.09.9
      run: |
        sudo apt-get update
        sudo apt-get install -y \
            apt-transport-https \
            ca-certificates \
            curl \
            gnupg-agent \
            software-properties-common
        
        curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
        
        sudo add-apt-repository \
          "deb [arch=amd64] https://download.docker.com/linux/ubuntu \
          $(lsb_release -cs) \
          stable"
        
        sudo apt-get update
        sudo apt-get install -y docker-ce=5:18.09.9~3-0~ubuntu-$(lsb_release -cs) docker-ce-cli=5:18.09.9~3-0~ubuntu-$(lsb_release -cs) containerd.io
        
    - name: Pull Docker Images and Package
      run: |
        images="${{ github.event.inputs.docker_images }}"
          IFS=',' read -r -a image_array <<< "$images"
          for image in "${image_array[@]}"; do
            docker pull "${image}" --platform "linux/arm64"
            image_name="${image//\//_}"
            image_name="${image_name//:/_}"
            docker save "${image}" -o "${image_name}-arm64.tar"
            gzip -c "${image_name}-arm64.tar" > "${image_name}-arm64.tar.gz"
            rm "${image_name}-arm64.tar"
          done

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: my-artifact
        path: ${{ github.workspace }}/*.tar.gz
        retention-days: 1  # 将保留天数设置为 1 天 最多可设置90天

